Add ability to use a mirror repo for downloading NodeJS installers
jenkinsci/nodejs-plugin pull request #39
Opened 2021-01-13 14:30 UTC by Stetchy

This PR adds functionality for a user to enter a mirror repo when configuring the NodeJS plugin to automatically download and install packages from that repo rather than the official NodeJS repo located at https://nodejs.org/dist.

Reasoning behind this functionality is:
 - Some users may not be able to reach the official repo due to their jurisdiction and may need to use a mirror such as Taobao.
 - Some users working in companies may use software such as Artifactory to mirror public repos instead of allowing internet access.
 
 As this is my first time contributing and I couldn't find much documentation on contributing, I need a small bit of help to get this ready.
 
 I've completed the functionality, it's pretty simple, but in terms of testing I am not sure how to reliably test that the url is being set to the mirror repo, when writing a test the installable url is being set as a temp file. Also, when adding it to the JCasCTests it errors out, not expecting the mirrorRepo option to be available in JCasC, not sure why.
 
 Any pointers on the above would be great, I'd love to get this merged in :)

2021-01-13 14:43 UTC, nfalco79 commented
If your company policies does not allow exit to the internet and force to allowed mirror (tipically I expect there is a proxy that access or deny based on white/black list) instead of select "Install automatically" you can set the direct link to the archive.
I do not see how to you had resolve the same issue for JDK, Maven or other tools where is not possible change the certified source. Since I do not see this option available in any other tools I would doubt that the mirror ensure the same content and logic or the original.
Actually I'm not for this approach

2021-01-13 14:53 UTC, Stetchy commented
Hi @nfalco79, 

Setting the direct link to the archive doesn't allow installation of global npm packages too. 
Also, when setting a direct link to the zip file you need the complete link for each version, whereas doing it this way allows for use of the drop down and auto-creation of the download URL for whatever version the user chooses.

You can see something similar done when, in NPM we can change the registry URL - it is the same premise. http://npm.taobao.org/mirrors/node is a great example of a mirror repo. With these mirrors it is expected to have the same structure as the NodeJS repo, just with a different base URL. This is why I chose to change even the /dist path, as with mirror repos it doesn't usually exist.

2021-01-15 07:38 UTC, nfalco79 commented
>Setting the direct link to the archive doesn't allow installation of global npm packages too.

I inherited that behaviour. Any run can perfomr npm install <package> -g and I can not avoid the specified package is installed on NodeJS tool folder that could raise concurrecy issues.

Anyway I understand the case, also my company use Artifactory but we did not use it as mirror. I would ask to you:
* to open a feature on https://issues.jenkins-ci.org/ component nodejs-plugin
* support basic authentication for the mirror (user password credential kind only because download is URL based)
* investigate if there are issue with self-signed certificates and in case if is possible allow them

Last two requirements because it's easy that peoples will ask.

I would leave if possible untouch the Install from secured souce nodejs.org and actual configuration, instead add new Installer specific for mirrored repositories with credentials and self-signed options where the mirror field URL is required and a clear description how the URL work and the expected content. Something like this:
![immagine](https://user-images.githubusercontent.com/4160180/104695025-5f002080-570c-11eb-994b-b8d3d7d375d7.png)

2021-01-15 12:00 UTC, Stetchy commented
Hi @nfalco79,

Will do the above.

I opened an issue here https://issues.jenkins.io/browse/JENKINS-64630 regarding adding the functionality to Jenkins Core. 

I can work on the above features, and in the meantime see what the response is to the ticket above and then we can decide whether we want to add the functionality here, or wait for it to come from core.

Does this sound okay to you?

2021-01-15 12:37 UTC, nfalco79 commented
I agree. I do not know if mirroring is applicable to any installation tools.
Anyway if you want proceed it would be great. Extending MirrorNodeJSInstaller should enogth to obation the same behavior but a different Installer totally compatible with other code. It is also possible include the jelly page of base NodeJSInstaller class to avoid duplications.

2021-01-16 00:00 UTC, Stetchy commented
Cool - I've started work on it and it's looking good, just need to look into the self-signed certs. 

I've created the ticket https://issues.jenkins.io/browse/JENKINS-64646 - would you like me to close this PR then reopen when ready with new criteria in the ticket?

2021-01-27 12:33 UTC, nfalco79 requested changes

2021-01-27 12:33 UTC, nfalco79 commented on src/main/java/jenkins/plugins/nodejs/tools/MirrorNodeJSInstaller.java
> +    public static final class DescriptorImpl extends DownloadFromUrlInstaller.DescriptorImpl<MirrorNodeJSInstaller> { // NOSONAR
Add check method for mirrorURL like
`public FormValidation doCheckMirrorURL(@CheckForNull @QueryParameter final String mirrorURL)` where if empty than return an form validation error message or check if the site exists and so on...warn about no env variable are accepted

2021-01-27 12:33 UTC, nfalco79 commented on src/main/resources/jenkins/plugins/nodejs/tools/MirrorNodeJSInstaller/config.properties
> +# Copyright (c) 2016, Riain Condon
2021

2021-01-31 20:23 UTC, Stetchy commented on src/main/resources/jenkins/plugins/nodejs/tools/MirrorNodeJSInstaller/config.properties
> +ignoreTlsErrors.title=Don't Verify TLS
Resolved

2021-01-31 20:24 UTC, Stetchy commented on src/main/resources/jenkins/plugins/nodejs/tools/MirrorNodeJSInstaller/config.properties
> +# Copyright (c) 2016, Riain Condon
Resolved

2021-01-31 20:24 UTC, Stetchy commented on src/main/resources/jenkins/plugins/nodejs/Messages.properties
> +MirrorNodeJSInstaller.DescriptorImpl.displayName=Install from mirror
Resolved

2021-01-31 20:26 UTC, Stetchy commented on src/main/java/jenkins/plugins/nodejs/tools/MirrorNodeJSInstaller.java
> +    public static final class DescriptorImpl extends DownloadFromUrlInstaller.DescriptorImpl<MirrorNodeJSInstaller> { // NOSONAR
Not sure what you mean about the abstract class - I've extended the NodeJS DescriptorImpl, so I don't have to dupe code, not sure making it abstract while extending DownloadFromUrlInstaller will prevent dupes

2021-01-31 20:26 UTC, Stetchy commented on src/main/java/jenkins/plugins/nodejs/tools/MirrorNodeJSInstaller.java
> +    public static final class DescriptorImpl extends DownloadFromUrlInstaller.DescriptorImpl<MirrorNodeJSInstaller> { // NOSONAR
Added some formvalidation as a start

2021-01-31 20:26 UTC, Stetchy commented on src/main/java/jenkins/plugins/nodejs/tools/MirrorNodeJSInstaller.java
> +            boolean useMirror = !mirrorUrl.isEmpty();
Removed

2021-01-31 20:31 UTC, Stetchy commented on src/main/java/jenkins/plugins/nodejs/tools/MirrorNodeJSInstaller.java
> +    private String mirrorUrl;
Resolved acronyms

2021-01-31 20:31 UTC, Stetchy commented on src/main/java/jenkins/plugins/nodejs/tools/MirrorNodeJSInstaller.java
> +    public MirrorNodeJSInstaller(String id, String npmPackages, long npmPackagesRefreshHours, boolean force32Bit, String mirrorUrl) {
Resolved

2021-01-31 20:31 UTC, Stetchy commented on src/main/java/jenkins/plugins/nodejs/tools/MirrorNodeJSInstaller.java
> +package jenkins.plugins.nodejs.tools;
Resolved

2021-01-31 20:32 UTC, Stetchy commented on README.md
> +    If you cannot use the official NodeJS repo to install, enter your mirror repo in this section. For example, some users may need to use a mirror due to their jurisdiction.
Resolved

2021-01-31 20:32 UTC, Stetchy commented
Resolved most of the comments, sorry it's taking a bit longer than I expected to get everything done. Quite busy and also figuring out how to do certain things but will get it done asap

2021-02-01 09:03 UTC, nfalco79 requested changes

2021-02-01 09:03 UTC, nfalco79 commented on src/main/java/jenkins/plugins/nodejs/tools/MirrorNodeJSInstaller.java
> +    public static final class DescriptorImpl extends NodeJSInstaller.DescriptorImpl { // NOSONAR
this descriptor must be typed,. What I mean in my last comment is extends an (new) abstract class parametric in T that have the 3 common methods.

2021-02-01 09:03 UTC, nfalco79 commented on src/main/java/jenkins/plugins/nodejs/tools/NodeJSInstaller.java
> -    private boolean installIfNecessaryMSI(FilePath expected, URL archive, TaskListener listener, String message) throws IOException, InterruptedException {
the reason of these changes?

2021-03-13 21:56 UTC, closed without merging